/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchesRouteRouteImport } from './routes/watches/route'
import { Route as VikingbotRouteRouteImport } from './routes/vikingbot/route'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as TasksRouteRouteImport } from './routes/tasks/route'
import { Route as SkillsRouteRouteImport } from './routes/skills/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SessionsRouteRouteImport } from './routes/sessions/route'
import { Route as RetrievalRouteRouteImport } from './routes/retrieval/route'
import { Route as RequestLogsRouteRouteImport } from './routes/request-logs/route'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as PlaygroundRouteRouteImport } from './routes/playground/route'
import { Route as MonitoringRouteRouteImport } from './routes/monitoring/route'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as AgentExperienceRouteRouteImport } from './routes/agent-experience/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VikingbotIndexRouteImport } from './routes/vikingbot/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as CompileIndexRouteImport } from './routes/compile/index'
import { Route as AgentExperienceIndexRouteImport } from './routes/agent-experience/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as OauthVerifyRouteImport } from './routes/oauth/verify'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as CompileNewRouteImport } from './routes/compile/new'
import { Route as AgentExperienceExperienceUriRouteImport } from './routes/agent-experience/$experienceUri'
import { Route as CompileTasksTaskIdRouteImport } from './routes/compile/tasks/$taskId'

const WatchesRouteRoute = WatchesRouteRouteImport.update({
  id: '/watches',
  path: '/watches',
  getParentRoute: () => rootRouteImport,
} as any)
const VikingbotRouteRoute = VikingbotRouteRouteImport.update({
  id: '/vikingbot',
  path: '/vikingbot',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRouteRoute = TasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRouteRoute = SkillsRouteRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRouteRoute = SessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrievalRouteRoute = RetrievalRouteRouteImport.update({
  id: '/retrieval',
  path: '/retrieval',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestLogsRouteRoute = RequestLogsRouteRouteImport.update({
  id: '/request-logs',
  path: '/request-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRouteRoute = PlaygroundRouteRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRouteRoute = MonitoringRouteRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentExperienceRouteRoute = AgentExperienceRouteRouteImport.update({
  id: '/agent-experience',
  path: '/agent-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VikingbotIndexRoute = VikingbotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VikingbotRouteRoute,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const CompileIndexRoute = CompileIndexRouteImport.update({
  id: '/compile/',
  path: '/compile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentExperienceIndexRoute = AgentExperienceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentExperienceRouteRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const OauthVerifyRoute = OauthVerifyRouteImport.update({
  id: '/oauth/verify',
  path: '/oauth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const CompileNewRoute = CompileNewRouteImport.update({
  id: '/compile/new',
  path: '/compile/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentExperienceExperienceUriRoute =
  AgentExperienceExperienceUriRouteImport.update({
    id: '/$experienceUri',
    path: '/$experienceUri',
    getParentRoute: () => AgentExperienceRouteRoute,
  } as any)
const CompileTasksTaskIdRoute = CompileTasksTaskIdRouteImport.update({
  id: '/compile/tasks/$taskId',
  path: '/compile/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-experience': typeof AgentExperienceRouteRouteWithChildren
  '/home': typeof HomeRouteRoute
  '/monitoring': typeof MonitoringRouteRoute
  '/playground': typeof PlaygroundRouteRoute
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/request-logs': typeof RequestLogsRouteRoute
  '/retrieval': typeof RetrievalRouteRoute
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/skills': typeof SkillsRouteRoute
  '/tasks': typeof TasksRouteRoute
  '/users': typeof UsersRouteRoute
  '/vikingbot': typeof VikingbotRouteRouteWithChildren
  '/watches': typeof WatchesRouteRoute
  '/agent-experience/$experienceUri': typeof AgentExperienceExperienceUriRoute
  '/compile/new': typeof CompileNewRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/verify': typeof OauthVerifyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/agent-experience/': typeof AgentExperienceIndexRoute
  '/compile/': typeof CompileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/vikingbot/': typeof VikingbotIndexRoute
  '/compile/tasks/$taskId': typeof CompileTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRoute
  '/monitoring': typeof MonitoringRouteRoute
  '/playground': typeof PlaygroundRouteRoute
  '/request-logs': typeof RequestLogsRouteRoute
  '/retrieval': typeof RetrievalRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/skills': typeof SkillsRouteRoute
  '/tasks': typeof TasksRouteRoute
  '/users': typeof UsersRouteRoute
  '/watches': typeof WatchesRouteRoute
  '/agent-experience/$experienceUri': typeof AgentExperienceExperienceUriRoute
  '/compile/new': typeof CompileNewRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/verify': typeof OauthVerifyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/agent-experience': typeof AgentExperienceIndexRoute
  '/compile': typeof CompileIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/vikingbot': typeof VikingbotIndexRoute
  '/compile/tasks/$taskId': typeof CompileTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-experience': typeof AgentExperienceRouteRouteWithChildren
  '/home': typeof HomeRouteRoute
  '/monitoring': typeof MonitoringRouteRoute
  '/playground': typeof PlaygroundRouteRoute
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/request-logs': typeof RequestLogsRouteRoute
  '/retrieval': typeof RetrievalRouteRoute
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/skills': typeof SkillsRouteRoute
  '/tasks': typeof TasksRouteRoute
  '/users': typeof UsersRouteRoute
  '/vikingbot': typeof VikingbotRouteRouteWithChildren
  '/watches': typeof WatchesRouteRoute
  '/agent-experience/$experienceUri': typeof AgentExperienceExperienceUriRoute
  '/compile/new': typeof CompileNewRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/verify': typeof OauthVerifyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/agent-experience/': typeof AgentExperienceIndexRoute
  '/compile/': typeof CompileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/vikingbot/': typeof VikingbotIndexRoute
  '/compile/tasks/$taskId': typeof CompileTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-experience'
    | '/home'
    | '/monitoring'
    | '/playground'
    | '/projects'
    | '/request-logs'
    | '/retrieval'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/users'
    | '/vikingbot'
    | '/watches'
    | '/agent-experience/$experienceUri'
    | '/compile/new'
    | '/oauth/consent'
    | '/oauth/verify'
    | '/projects/$projectId'
    | '/agent-experience/'
    | '/compile/'
    | '/projects/'
    | '/sessions/'
    | '/vikingbot/'
    | '/compile/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/monitoring'
    | '/playground'
    | '/request-logs'
    | '/retrieval'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/users'
    | '/watches'
    | '/agent-experience/$experienceUri'
    | '/compile/new'
    | '/oauth/consent'
    | '/oauth/verify'
    | '/projects/$projectId'
    | '/agent-experience'
    | '/compile'
    | '/projects'
    | '/sessions'
    | '/vikingbot'
    | '/compile/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/agent-experience'
    | '/home'
    | '/monitoring'
    | '/playground'
    | '/projects'
    | '/request-logs'
    | '/retrieval'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/users'
    | '/vikingbot'
    | '/watches'
    | '/agent-experience/$experienceUri'
    | '/compile/new'
    | '/oauth/consent'
    | '/oauth/verify'
    | '/projects/$projectId'
    | '/agent-experience/'
    | '/compile/'
    | '/projects/'
    | '/sessions/'
    | '/vikingbot/'
    | '/compile/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentExperienceRouteRoute: typeof AgentExperienceRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRoute
  MonitoringRouteRoute: typeof MonitoringRouteRoute
  PlaygroundRouteRoute: typeof PlaygroundRouteRoute
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  RequestLogsRouteRoute: typeof RequestLogsRouteRoute
  RetrievalRouteRoute: typeof RetrievalRouteRoute
  SessionsRouteRoute: typeof SessionsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRoute
  SkillsRouteRoute: typeof SkillsRouteRoute
  TasksRouteRoute: typeof TasksRouteRoute
  UsersRouteRoute: typeof UsersRouteRoute
  VikingbotRouteRoute: typeof VikingbotRouteRouteWithChildren
  WatchesRouteRoute: typeof WatchesRouteRoute
  CompileNewRoute: typeof CompileNewRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthVerifyRoute: typeof OauthVerifyRoute
  CompileIndexRoute: typeof CompileIndexRoute
  CompileTasksTaskIdRoute: typeof CompileTasksTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watches': {
      id: '/watches'
      path: '/watches'
      fullPath: '/watches'
      preLoaderRoute: typeof WatchesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vikingbot': {
      id: '/vikingbot'
      path: '/vikingbot'
      fullPath: '/vikingbot'
      preLoaderRoute: typeof VikingbotRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrieval': {
      id: '/retrieval'
      path: '/retrieval'
      fullPath: '/retrieval'
      preLoaderRoute: typeof RetrievalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-logs': {
      id: '/request-logs'
      path: '/request-logs'
      fullPath: '/request-logs'
      preLoaderRoute: typeof RequestLogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-experience': {
      id: '/agent-experience'
      path: '/agent-experience'
      fullPath: '/agent-experience'
      preLoaderRoute: typeof AgentExperienceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vikingbot/': {
      id: '/vikingbot/'
      path: '/'
      fullPath: '/vikingbot/'
      preLoaderRoute: typeof VikingbotIndexRouteImport
      parentRoute: typeof VikingbotRouteRoute
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/compile/': {
      id: '/compile/'
      path: '/compile'
      fullPath: '/compile/'
      preLoaderRoute: typeof CompileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-experience/': {
      id: '/agent-experience/'
      path: '/'
      fullPath: '/agent-experience/'
      preLoaderRoute: typeof AgentExperienceIndexRouteImport
      parentRoute: typeof AgentExperienceRouteRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/oauth/verify': {
      id: '/oauth/verify'
      path: '/oauth/verify'
      fullPath: '/oauth/verify'
      preLoaderRoute: typeof OauthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compile/new': {
      id: '/compile/new'
      path: '/compile/new'
      fullPath: '/compile/new'
      preLoaderRoute: typeof CompileNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-experience/$experienceUri': {
      id: '/agent-experience/$experienceUri'
      path: '/$experienceUri'
      fullPath: '/agent-experience/$experienceUri'
      preLoaderRoute: typeof AgentExperienceExperienceUriRouteImport
      parentRoute: typeof AgentExperienceRouteRoute
    }
    '/compile/tasks/$taskId': {
      id: '/compile/tasks/$taskId'
      path: '/compile/tasks/$taskId'
      fullPath: '/compile/tasks/$taskId'
      preLoaderRoute: typeof CompileTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentExperienceRouteRouteChildren {
  AgentExperienceExperienceUriRoute: typeof AgentExperienceExperienceUriRoute
  AgentExperienceIndexRoute: typeof AgentExperienceIndexRoute
}

const AgentExperienceRouteRouteChildren: AgentExperienceRouteRouteChildren = {
  AgentExperienceExperienceUriRoute: AgentExperienceExperienceUriRoute,
  AgentExperienceIndexRoute: AgentExperienceIndexRoute,
}

const AgentExperienceRouteRouteWithChildren =
  AgentExperienceRouteRoute._addFileChildren(AgentExperienceRouteRouteChildren)

interface ProjectsRouteRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

interface SessionsRouteRouteChildren {
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteRouteChildren: SessionsRouteRouteChildren = {
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteRouteWithChildren = SessionsRouteRoute._addFileChildren(
  SessionsRouteRouteChildren,
)

interface VikingbotRouteRouteChildren {
  VikingbotIndexRoute: typeof VikingbotIndexRoute
}

const VikingbotRouteRouteChildren: VikingbotRouteRouteChildren = {
  VikingbotIndexRoute: VikingbotIndexRoute,
}

const VikingbotRouteRouteWithChildren = VikingbotRouteRoute._addFileChildren(
  VikingbotRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentExperienceRouteRoute: AgentExperienceRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRoute,
  MonitoringRouteRoute: MonitoringRouteRoute,
  PlaygroundRouteRoute: PlaygroundRouteRoute,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  RequestLogsRouteRoute: RequestLogsRouteRoute,
  RetrievalRouteRoute: RetrievalRouteRoute,
  SessionsRouteRoute: SessionsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRoute,
  SkillsRouteRoute: SkillsRouteRoute,
  TasksRouteRoute: TasksRouteRoute,
  UsersRouteRoute: UsersRouteRoute,
  VikingbotRouteRoute: VikingbotRouteRouteWithChildren,
  WatchesRouteRoute: WatchesRouteRoute,
  CompileNewRoute: CompileNewRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthVerifyRoute: OauthVerifyRoute,
  CompileIndexRoute: CompileIndexRoute,
  CompileTasksTaskIdRoute: CompileTasksTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
